#!/bin/bash

# Script for creating the relacs website in WEBDEST from the templates
# in WEBBASE.
# (c) 2008 by Jan Benda

RELACSBASE=../relacs/trunk
WEBBASE=web
WEBDEST=relacsweb

# directories and names for the main menu:
MAINMENU=".:Home \
features:Features \
screenshots:Screenshots \
download:Download \
doc:Documentation \
plugins:Plugins \
faq:FAQ \
publications:Publications \
contributors:Contributors \
links:Links"

# directories with index files:
INDEXDIRS="features \
screenshots \
download \
doc \
faq \
publications \
contributors
links"

# directories and descriptions of plugin sets:
PLUGINSETS="base:Base \
calibration:Calibration \
ephys:EPhys \
acoustic:Acoustic \
auditory:Auditory \
auditoryprojects:Auditory-Projects \
patchclamp:Patch-Clamp \
linuxdevices/comedi:Comedi \
linuxdevices/nieseries:NI-ESeries \
linuxdevices/attcs3310:Att-CS3310 \
linuxdevices/misc:Miscellaneous"

# names of plugin types:
PLUGINTYPES="RePro \
Control \
Filter \
Detector \
Model \
AnalogInput \
AnalogOutput \
Attenuator \
Attenuate \
Manipulator \
Temperature \
Device \
Lib"

# clean previous web site:
CLEANALL="no"
if test "x$1" = "x-d"; then
  CLEANALL="yes"
  shift
fi

# no plugins:
DOPLUGINS="yes"
if test "x$1" = "x-n"; then
  DOPLUGINS="no"
  shift
fi


##### the script: ########################################################

function insertnavigation 
{
    local CURRENTDIR="$1"
    local LINK="$2"
    local BASEDIR="$3"

    local MENUSAVEIFS="$IFS"
    echo "    <td class="navigation">"
    echo "      <ul>"
    IFS=" "
    for MENUENTRY in $MAINMENU; do
        local MENUDIR=${MENUENTRY%%:*}
        local MENUNAME="${MENUENTRY##*:}"
	if test "x$MENUDIR" = "x$CURRENTDIR" ; then
   	    local TEXT="<a href="$LINK">$MENUNAME</a>"
	    if test "x$LINK" = "xno" ; then
		TEXT="$MENUNAME"
	    fi
	    if test -f $WEBBASE/$MENUDIR/menu.tmpl ; then
                echo "        <li>$TEXT"
	        cat $WEBBASE/$MENUDIR/menu.tmpl
                echo "        </li>"
	    else
                echo "        <li>$TEXT</li>"
            fi
        else
	    if test "x$MENUDIR" = "x." ; then
		MENUDIR=index.html
	    fi
            echo "        <li><a href="${BASEDIR}${MENUDIR}">$MENUNAME</a></li>"
        fi
    done
    echo "      </ul>"
    echo "    </td>"
    IFS="$MENUSAVEIFS"
}


SAVEIFS="$IFS"

# clean and create destination folder:
if test $CLEANALL = yes; then
  echo "clean and setup destination folder $WEBDEST ..."
  rm -r -f $WEBDEST
else
  echo "setup destination folder $WEBDEST ..."
fi
mkdir -p $WEBDEST

# create subdirectories:
for dir in $WEBBASE/*; do
  if test -d $dir && ! test -d $WEBDEST/${dir#$WEBBASE/}; then
    echo "creat directory ${dir#$WEBBASE/} ..."
    mkdir $WEBDEST/${dir#$WEBBASE/}
  fi
done

# copy html, css, png, and pdf files:
echo "copy html, css, png, and pdf files to $WEBBASE ..."
for file in $(find $WEBBASE -name '*.html' -o -name '*.css' -o -name '*.png' -o -name '*.jpg' -o -name '*.pdf'); do
    cp -p $file $WEBDEST/${file#$WEBBASE/}
done

# link to documentation:
echo "create link to RELACS documentation ... "
cd $WEBDEST/doc
ln -f -s ../../$RELACSBASE/doc/html reference
cd - > /dev/null

# translate other index.html files:
for DIR in $INDEXDIRS; do
    echo "translate $DIR/index.html ..."
    IFS=""
    while read LINE; do
	if [ $(expr match "$LINE" "INSERTHEADER.*") -gt 0 ]; then
	    sed -e 's|BASEDIR|../|' $WEBBASE/header.tmpl
	elif [ $(expr match "$LINE" "INSERTNAVIGATION.*") -gt 0 ]; then
	    insertnavigation "$DIR" "no" "../"
	else
	    echo "$LINE"
	fi
    done < $WEBBASE/$DIR/index.tmpl > $WEBDEST/$DIR/index.html
    IFS="$SAVEIFS"
done

# NEWS in index.html:
echo "create main index.html file ... "
FILE="$RELACSBASE/NEWS"
IFS=""
while read LINE; do
    if [ $(expr match "$LINE" "INSERTHEADER.*") -gt 0 ]; then
	sed -e 's|BASEDIR||' $WEBBASE/header.tmpl
    elif [ $(expr match "$LINE" "INSERTNAVIGATION.*") -gt 0 ]; then
	insertnavigation "." "no" ""
    elif [ $(expr match "$LINE" "INSERTNEWS.*") -gt 0 ]; then
	COUNT=0
        DDOPEN="no"
	while read CLINE; do
	    if [ $(expr match "$CLINE" "\w.*") -gt 0 ]; then
		[ $COUNT -gt 1 ] && break;
		if [ $DDOPEN = "yes" ]; then
		    echo "    </dd>"
		    echo ""
		    DDOPEN="no"
		fi
		echo "    <dt>$CLINE</dt>"
		echo "    <dd>"
		DDOPEN="yes"
		let COUNT+=1
	    else
		[ $(expr match "$CLINE" ".*\w.*") -gt 0 ] && echo "    $CLINE"
	    fi
	done < $FILE
	[ $DDOPEN = "yes" ] && echo "    </dd>"
    else
	echo "$LINE"
    fi
done < $WEBBASE/index.tmpl > $WEBDEST/index.html
IFS="$SAVEIFS"

# README, INSTALL:
echo "format README and INSTALL files ... "
for FILE in $RELACSBASE/README $RELACSBASE/INSTALL; do
    WEB=$(echo $FILE | tr [:upper:] [:lower:])
    WEB=${WEB##*/}
    IFS=""
    while read LINE; do
	if [ $(expr match "$LINE" "INSERTHEADER.*") -gt 0 ]; then
	    sed -e 's|BASEDIR|../|' $WEBBASE/header.tmpl
	elif [ $(expr match "$LINE" "INSERTNAVIGATION.*") -gt 0 ]; then
	    insertnavigation "doc" "no" "../"
	elif [ $(expr match "$LINE" ".*<pre>.*") -gt 0 ]; then
	    echo "$LINE"
	    cat $FILE
	else
	    echo "$LINE"
	fi
    done < $WEBBASE/doc/$WEB.tmpl > $WEBDEST/doc/$WEB.html
    IFS="$SAVEIFS"
done

# changelog:
echo "format ChangeLog file ... "
FILE="$RELACSBASE/ChangeLog"
WEB=$(echo $FILE | tr [:upper:] [:lower:])
WEB=${WEB##*/}
IFS=""
DLOPEN="no"
DDOPEN="no"
while read LINE; do
    if [ $(expr match "$LINE" "INSERTHEADER.*") -gt 0 ]; then
	sed -e 's|BASEDIR|../|' $WEBBASE/header.tmpl
    elif [ $(expr match "$LINE" "INSERTNAVIGATION.*") -gt 0 ]; then
	insertnavigation "doc" "no" "../"
    elif [ $(expr match "$LINE" "INSERT.*") -gt 0 ]; then
	while read CLINE; do
	    [ $(expr match "$CLINE" "=====.*") -gt 0 ] && break
	    if [ $(expr match "$CLINE" "------.*") -gt 0 ]; then
		if [ $DDOPEN = "yes" ]; then
		    echo "      </dd>"
		    DDOPEN="no";
		fi
		if [ $DLOPEN = "yes" ]; then
		    echo "    </dl>"
		    DLOPEN="no"
		fi
		echo ""
	    elif [ $(expr match "$CLINE" "Version.*") -gt 0 ]; then
		echo "    <h3>$CLINE</h3>"
		echo "    <dl>"
		DLOPEN="yes"
	    elif [ $(expr match "$CLINE" "20.*") -gt 0 ]; then
		if [ $DDOPEN = "yes" ]; then
		    echo "      </dd>"
		    DDOPEN="no";
		fi
		echo "      <dt>$CLINE</dt>"
	    elif [ $(expr match "$CLINE" ".*\w.*") -gt 0 ]; then
		if echo "$CLINE" | grep '^\s*[A-Z]' &> /dev/null; then
		    if [ $DDOPEN = "no" ]; then
			echo "      <dd>"
			DDOPEN="yes";
		    else
			echo "      </dd>"
			echo "      <dd>"
		    fi
		fi
		if [ $DDOPEN = "no" ]; then
		    echo "      <dd>"
		    DDOPEN="yes";
		fi
		echo "        $CLINE"
	    fi
	done < $FILE
	[ $DDOPEN = "yes" ] && echo "      </dd>"
	[ $DLOPEN = "yes" ] && echo "    </dl>"
    else
	echo "$LINE"
    fi
done < $WEBBASE/doc/$WEB.tmpl > $WEBDEST/doc/$WEB.html
IFS="$SAVEIFS"

# NEWS in doc/news.html:
echo "format NEWS file ... "
FILE="$RELACSBASE/NEWS"
IFS=""
while read LINE; do
    if [ $(expr match "$LINE" "INSERTHEADER.*") -gt 0 ]; then
	sed -e 's|BASEDIR|../|' $WEBBASE/header.tmpl
    elif [ $(expr match "$LINE" "INSERTNAVIGATION.*") -gt 0 ]; then
	    insertnavigation "doc" "no" "../"
    elif [ $(expr match "$LINE" "INSERTNEWS.*") -gt 0 ]; then
        DDOPEN="no"
	while read CLINE; do
	    if [ $(expr match "$CLINE" "\w.*") -gt 0 ]; then
		if [ $DDOPEN = "yes" ]; then
		    echo "    </dd>"
		    echo ""
		    DDOPEN="no"
		fi
		echo "    <dt>$CLINE</dt>"
		echo "    <dd>"
		DDOPEN="yes"
	    else
		[ $(expr match "$CLINE" ".*\w.*") -gt 0 ] && echo "    $CLINE"
	    fi
	done < $FILE
	[ $DDOPEN = "yes" ] && echo "    </dd>"
    else
	echo "$LINE"
    fi
done < $WEBBASE/doc/news.tmpl > $WEBDEST/doc/news.html
IFS="$SAVEIFS"


if test $DOPLUGINS = yes; then

# plugin navigation:
echo "extract plugin set navigation ... "
echo "          <ul>" > navigation.tmp
echo "            <li class="title"><a href=\"../index.html#pluginsets\">By Plugin Set</a></li>" >> navigation.tmp
for SET in $PLUGINSETS; do
    DIR=${SET%%:*}
    DESCR=${SET##*:}
    echo "            <li><a href=\"../${DIR##*/}\">$DESCR</a></li>"
done >> navigation.tmp
echo "            <li class="title"><a href=\"../index.html#plugintypes\">By Plugin Type</a></li>" >> navigation.tmp
for TYPE in $PLUGINTYPES; do
    echo "            <li><a href=\"../$(echo $TYPE | tr [:upper:] [:lower:])s.html\">$TYPE</a></li>"
done >> navigation.tmp
echo "          </ul>" >> navigation.tmp

DATE="$(date)"

# plugin index:
echo "create plugin set main index ... "
IFS=""
while read INDEXLINE; do
    IFS="$SAVEIFS"
    if [ $(expr match "$INDEXLINE" "PLUGINSETS.*") -gt 0 ]; then
	echo "    <ul>"
	for SET in $PLUGINSETS; do
	    DIR=${SET%%:*}
	    DESCR=${SET##*:}
	    INTRO="$(sed -n '/\\brief/{s/\\brief //; p}' $RELACSBASE/plugins/$DIR/doc/${DIR##*/}.doc)"
	    echo "      <li><a href=\"${DIR##*/}\">$DESCR:</a> <span class=\"brief\">$INTRO</span></li>"
	done
	echo "    </ul>"
    elif [ $(expr match "$INDEXLINE" "PLUGINTYPES.*") -gt 0 ]; then
	echo "    <ul>"
	for PLUGINTYPE in $PLUGINTYPES; do
	    echo "      <li><a href=\"$(echo $PLUGINTYPE | tr [:upper:] [:lower:])s.html\">$PLUGINTYPE</li>"
	done
	echo "    </ul>"
    elif [ $(expr match "$INDEXLINE" "INSERTHEADER.*") -gt 0 ]; then
	sed -e 's|BASEDIR|../|' $WEBBASE/header.tmpl
    elif [ $(expr match "$INDEXLINE" "INSERTNAVIGATION.*") -gt 0 ]; then
	sed 's|\.\./||' navigation.tmp > $WEBBASE/plugins/menu.tmpl 
	insertnavigation "plugins" "no" "../"
    else
	echo "${INDEXLINE/DATE/$DATE}"
    fi
    IFS=""
done < $WEBBASE/plugins/index.tmpl > $WEBDEST/plugins/index.html
IFS="$SAVEIFS"

# plugin descriptions:
rm -f *plugins.dat
for SET in $PLUGINSETS; do
    DIR=${SET%%:*}
    DESCR=${SET##*:}
    echo "create index for plugin set $DESCR ... "
    mkdir -p $WEBDEST/plugins/${DIR##*/}
    cp -u $RELACSBASE/plugins/$DIR/help/*.jpg $RELACSBASE/plugins/$DIR/help/*.png $WEBDEST/plugins/${DIR##*/}/ 2> /dev/null
    IFS=""
    while read INDEXLINE; do
	IFS="$SAVEIFS"
	if [ $(expr match "$INDEXLINE" ".*INSERT HERE.*") -gt 0 ]; then
	    echo "    <h2>$DESCR Plugins</h2>"
	    echo ""
	    if [ -f $RELACSBASE/plugins/$DIR/doc/${DIR##*/}.doc ]; then
		echo "<p>"
		sed -n '/\\brief/{s/\\brief //; p}' $RELACSBASE/plugins/$DIR/doc/${DIR##*/}.doc
		echo "</p>"
		echo ""
	    fi
	    if [ -d $RELACSBASE/plugins/$DIR/help ]; then
		echo "    <ul>"
		for PLUGIN in $RELACSBASE/plugins/$DIR/help/*.html; do
 	            PLUGINFILE=${PLUGIN##*/}
		    PLUGINNAME=${PLUGINFILE%%.*}
		    PLUGINNAME=${PLUGINNAME##*-}
                    PLUGINTYPE="$(sed -n -e "/<h2>/{s|<h2>\(.*\) \+\[\(.*\)\]</h2>|\2|; p;}" $PLUGIN )"
		    PLUGINTYPEFILEBASE="$(echo $PLUGINTYPE | tr [:upper:] [:lower:])"
		    IFS=""
		    while read LINE; do
			if [ $(expr match "$LINE" ".*INSERT HERE.*") -gt 0 ]; then
			    sed -e  "1d; \$d; s|<h2>\(.*\) \+\[.*\]</h2>|<h2>\1<span class=\"pluginset\">\&nbsp;\&nbsp;[<a href=\"../${PLUGINTYPEFILEBASE}s.html\">$PLUGINTYPE</a>]\&nbsp;\&nbsp;[<a href=\"index.html\">$DESCR Plugins</a>]</span></h2>|" $PLUGIN
			elif [ $(expr match "$LINE" "INSERTHEADER.*") -gt 0 ]; then
			    sed -e 's|BASEDIR|../../|' $WEBBASE/header.tmpl
			elif [ $(expr match "$LINE" "INSERTNAVIGATION.*") -gt 0 ]; then
			    cp navigation.tmp $WEBBASE/plugins/menu.tmpl 
			    insertnavigation "plugins" "../index.html" "../../"
			else
			    LINE="${LINE/DATE/$DATE}"
			    echo "${LINE/PLUGINHEADER/$DESCR Plugins: $PLUGINNAME}"
			fi
		    done < $WEBBASE/plugins/plugin.tmpl > $WEBDEST/plugins/${DIR##*/}/$PLUGINFILE
		    IFS="$SAVEIFS"
		    echo "${DIR##*/}/$PLUGINFILE $PLUGINNAME $DESCR" >> ${PLUGINTYPEFILEBASE}plugins.dat
		    echo "      <li><a href=\"$PLUGINFILE\">$PLUGINNAME</a>&nbsp;[<a href=\"../${PLUGINTYPEFILEBASE}s.html\">$PLUGINTYPE</a>]: <span class=\"brief\">$(sed -n '/<h2>/,/<p>/p' $PLUGIN | sed '1d; $d;')</span></li>"
		done
		echo "    </ul>"
	    else
		echo "    <p>Sorry - no plugin descriptions available!</p>"
	    fi
        elif [ $(expr match "$INDEXLINE" "INSERTHEADER.*") -gt 0 ]; then
	    sed -e 's|BASEDIR|../../|' $WEBBASE/header.tmpl
        elif [ $(expr match "$INDEXLINE" "INSERTNAVIGATION.*") -gt 0 ]; then
	    cp navigation.tmp $WEBBASE/plugins/menu.tmpl 
	    insertnavigation "plugins" "../index.html" "../../"
	else
	    INDEXLINE="${INDEXLINE/DATE/$DATE}"
	    echo "${INDEXLINE/PLUGINHEADER/$DESCR Plugins}"
	fi
	IFS=""
    done < $WEBBASE/plugins/plugin.tmpl > $WEBDEST/plugins/${DIR##*/}/index.html
    IFS="$SAVEIFS"
done

# plugin type lists:
for PLUGINTYPE in $PLUGINTYPES; do
    echo "create $PLUGINTYPE plugins index ... "
    IFS=""
    while read INDEXLINE; do
	IFS="$SAVEIFS"
	if [ $(expr match "$INDEXLINE" "PLUGINSETS.*") -gt 0 ]; then
	    echo "    <ul>"
	    while read DIR NAME DESCR; do
		PLUGINSET=""
		for SET in $PLUGINSETS; do
		    PDIR=${SET%%:*}
		    PDESCR=${SET##*:}
		    if test "x$PDESCR" = "x$DESCR"; then
		      PLUGINSET="${PDIR##*/}"
		      break;
		    fi
		done
		echo "      <li><a href=\"${DIR}\">$NAME</a> [<a href=\"$PLUGINSET\">$DESCR</a>]: <span class=\"brief\">$(sed -n '/<h2>.*<span/,/<p>/p' $WEBDEST/plugins/$DIR | sed '1d; $d;')</span></li>"
            done < <(sort -k 2 $(echo $PLUGINTYPE | tr [:upper:] [:lower:])plugins.dat)
	    echo "    </ul>"
        elif [ $(expr match "$INDEXLINE" "INSERTHEADER.*") -gt 0 ]; then
	    sed -e 's|BASEDIR|../|' $WEBBASE/header.tmpl
        elif [ $(expr match "$INDEXLINE" "INSERTNAVIGATION.*") -gt 0 ]; then
	    sed 's|\.\./||' navigation.tmp > $WEBBASE/plugins/menu.tmpl 
	    insertnavigation "plugins" "index.html" "../"
	else
	    INDEXLINE="${INDEXLINE/DATE/$DATE}"
	    echo "${INDEXLINE/PLUGINHEADER/$PLUGINTYPE}"
	fi
	IFS=""
    done < $WEBBASE/plugins/plugintype.tmpl > $WEBDEST/plugins/$(echo $PLUGINTYPE | tr [:upper:] [:lower:])s.html
    IFS="$SAVEIFS"
done

rm -f *plugins.dat
rm navigation.tmp
rm $WEBBASE/plugins/menu.tmpl 

fi

echo
echo "Ready! You find the relacs website in $WEBDEST"
echo "Update the public website with"
echo "  rsync -avz relacsweb/ janbenda,relacs@web.sourceforge.net:htdocs/"

