#!/bin/bash

RELACSBASE=../relacs/trunk
WEBBASE=web
WEBDEST=relacsweb

# directories and descriptions of plugin sets:
PLUGINSETS="base:Base \
calibration:Calibration \
ephys:EPhys \
acoustic:Acoustic \
auditory:Auditory \
auditoryprojects:Auditory-Projects \
patchclamp:Patch-Clamp \
linuxdevices/comedi:Comedi \
linuxdevices/nieseries:NI-ESeries \
linuxdevices/attcs3310:Att-CS3310 \
linuxdevices/misc:Miscellaneous"

# names of plugin types:
PLUGINTYPES="RePro \
Control \
Filter \
Detector \
Model \
AnalogInput \
AnalogOutput \
Attenuator \
Attenuate \
Manipulator \
Temperature \
Device \
Lib"

SAVEIFS="$IFS"

cat > /dev/null <<EOF
echo "clean and setup destination folder $WEBDEST ..."

# clean and create destination folder:
rm -r -f $WEBDEST
mkdir $WEBDEST

# create subdirectories:
for dir in $WEBBASE/*; do
  if test -d $dir; then
    mkdir $WEBDEST/${dir#$WEBBASE/}
  fi
done

# copy html, css, png, and pdf files:
for file in $(find $WEBBASE -name '*.html' -o -name '*.css' -o -name '*.png' -o -name '*.jpg' -o -name '*.pdf'); do
    cp -p $file $WEBDEST/${file#$WEBBASE/}
done

# link to documentation:
echo "create link to RELACS documentation ... "
cd $WEBDEST/doc
ln -f -s ../../$RELACSBASE/doc/html reference
cd -

# NEWS in index.html:
echo "create main index.html file ... "
FILE="$RELACSBASE/NEWS"
IFS=""
while read LINE; do
    if [ $(expr match "$LINE" "INSERTNEWS.*") -gt 0 ]; then
	COUNT=0
        DDOPEN="no"
	while read CLINE; do
	    if [ $(expr match "$CLINE" "\w.*") -gt 0 ]; then
		[ $COUNT -gt 1 ] && break;
		if [ $DDOPEN = "yes" ]; then
		    echo "    </dd>"
		    echo ""
		    DDOPEN="no"
		fi
		echo "    <dt>$CLINE</dt>"
		echo "    <dd>"
		DDOPEN="yes"
		let COUNT+=1
	    else
		[ $(expr match "$CLINE" ".*\w.*") -gt 0 ] && echo "    $CLINE"
	    fi
	done < $FILE
	[ $DDOPEN = "yes" ] && echo "    </dd>"
    else
	echo "$LINE"
    fi
done < $WEBBASE/index.tmpl > $WEBDEST/index.html
IFS="$SAVEIFS"

# README, INSTALL:
echo "format README and INSTALL files ... "
for FILE in $RELACSBASE/README $RELACSBASE/INSTALL; do
    WEB=$(echo $FILE | tr [:upper:] [:lower:])
    WEB=${WEB##*/}
    IFS=""
    while read LINE; do
	echo "$LINE"
	if [ $(expr match "$LINE" ".*<pre>.*") -gt 0 ]; then
	    while read CLINE; do
		[ $(expr match "$CLINE" "=====.*") -gt 0 ] && break
		echo $CLINE
	    done < $FILE
	fi
    done < $WEBBASE/doc/$WEB.tmpl > $WEBDEST/doc/$WEB.html
    IFS="$SAVEIFS"
done

# changelog:
echo "format ChangeLog file ... "
FILE="$RELACSBASE/ChangeLog"
WEB=$(echo $FILE | tr [:upper:] [:lower:])
WEB=${WEB##*/}
IFS=""
DLOPEN="no"
DDOPEN="no"
while read LINE; do
    if [ $(expr match "$LINE" "INSERT.*") -gt 0 ]; then
	while read CLINE; do
	    [ $(expr match "$CLINE" "=====.*") -gt 0 ] && break
	    if [ $(expr match "$CLINE" "------.*") -gt 0 ]; then
		if [ $DDOPEN = "yes" ]; then
		    echo "      </dd>"
		    DDOPEN="no";
		fi
		if [ $DLOPEN = "yes" ]; then
		    echo "    </dl>"
		    DLOPEN="no"
		fi
		echo ""
	    elif [ $(expr match "$CLINE" "Version.*") -gt 0 ]; then
		echo "    <h3>$CLINE</h3>"
		echo "    <dl>"
		DLOPEN="yes"
	    elif [ $(expr match "$CLINE" "20.*") -gt 0 ]; then
		if [ $DDOPEN = "yes" ]; then
		    echo "      </dd>"
		    DDOPEN="no";
		fi
		echo "      <dt>$CLINE</dt>"
	    elif [ $(expr match "$CLINE" ".*\w.*") -gt 0 ]; then
		if echo "$CLINE" | grep '^\s*[A-Z]' &> /dev/null; then
		    if [ $DDOPEN = "no" ]; then
			echo "      <dd>"
			DDOPEN="yes";
		    else
			echo "      </dd>"
			echo "      <dd>"
		    fi
		fi
		if [ $DDOPEN = "no" ]; then
		    echo "      <dd>"
		    DDOPEN="yes";
		fi
		echo "        $CLINE"
	    fi
	done < $FILE
	[ $DDOPEN = "yes" ] && echo "      </dd>"
	[ $DLOPEN = "yes" ] && echo "    </dl>"
    else
	echo "$LINE"
    fi
done < $WEBBASE/doc/$WEB.tmpl > $WEBDEST/doc/$WEB.html
IFS="$SAVEIFS"

# NEWS in doc/news.html:
echo "format NEWS file ... "
FILE="$RELACSBASE/NEWS"
IFS=""
while read LINE; do
    if [ $(expr match "$LINE" "INSERTNEWS.*") -gt 0 ]; then
        DDOPEN="no"
	while read CLINE; do
	    if [ $(expr match "$CLINE" "\w.*") -gt 0 ]; then
		if [ $DDOPEN = "yes" ]; then
		    echo "    </dd>"
		    echo ""
		    DDOPEN="no"
		fi
		echo "    <dt>$CLINE</dt>"
		echo "    <dd>"
		DDOPEN="yes"
	    else
		[ $(expr match "$CLINE" ".*\w.*") -gt 0 ] && echo "    $CLINE"
	    fi
	done < $FILE
	[ $DDOPEN = "yes" ] && echo "    </dd>"
    else
	echo "$LINE"
    fi
done < $WEBBASE/doc/news.tmpl > $WEBDEST/doc/news.html
IFS="$SAVEIFS"


EOF

# plugin navigation:
echo "extract plugin set navigation ... "
echo "          <a href=\"../index.html#pluginsets\">By Plugin Set</a>" >> navigation.tmp
for SET in $PLUGINSETS; do
    DIR=${SET%%:*}
    DESCR=${SET##*:}
    echo "	    <li><a href=\"../${DIR##*/}\">$DESCR</a></li>"
done >> navigation.tmp
echo "          <a href=\"../index.html#plugintypes\">By Plugin Type</a>" >> navigation.tmp
for TYPE in $PLUGINTYPES; do
    echo "	    <li><a href=\"../$(echo $TYPE | tr [:upper:] [:lower:])s.html\">$TYPE</a></li>"
done >> navigation.tmp

DATE="$(date)"

# plugin index:
echo "create plugin set main index ... "
IFS=""
while read INDEXLINE; do
    IFS="$SAVEIFS"
    if [ $(expr match "$INDEXLINE" "PLUGINSETS.*") -gt 0 ]; then
	echo "    <ul>"
	for SET in $PLUGINSETS; do
	    DIR=${SET%%:*}
	    DESCR=${SET##*:}
	    INTRO="$(sed -n '/\\brief/{s/\\brief //; p}' $RELACSBASE/plugins/$DIR/doc/${DIR##*/}.doc)"
	    echo "      <li><a href=\"${DIR##*/}\">$DESCR:</a> <span class=\"brief\">$INTRO</span></li>"
	done
	echo "    </ul>"
    elif [ $(expr match "$INDEXLINE" "PLUGINTYPES.*") -gt 0 ]; then
	echo "    <ul>"
	for PLUGINTYPE in $PLUGINTYPES; do
	    echo "      <li><a href=\"$(echo $PLUGINTYPE | tr [:upper:] [:lower:])plugins.dat\">$PLUGINTYPE</li>"
	done
	echo "    </ul>"
    elif [ $(expr match "$INDEXLINE" "PLUGINNAVIGATION.*") -gt 0 ]; then
	sed 's|../||' navigation.tmp 
    else
	echo "${INDEXLINE/DATE/$DATE}"
    fi
    IFS=""
done < $WEBBASE/plugins/index.tmpl > $WEBDEST/plugins/index.html
IFS="$SAVEIFS"

# plugin descriptions:
rm -f *plugins.dat
for SET in $PLUGINSETS; do
    DIR=${SET%%:*}
    DESCR=${SET##*:}
    echo "create index for plugin set $DESCR ... "
    mkdir -p $WEBDEST/plugins/${DIR##*/}
    cp $RELACSBASE/plugins/$DIR/help/*.jpg $RELACSBASE/plugins/$DIR/help/*.png $WEBDEST/plugins/${DIR##*/}/
    IFS=""
    while read INDEXLINE; do
	IFS="$SAVEIFS"
	if [ $(expr match "$INDEXLINE" ".*INSERT HERE.*") -gt 0 ]; then
	    echo "    <h2>$DESCR Plugins</h2>"
	    echo ""
	    if [ -f $RELACSBASE/plugins/$DIR/doc/${DIR##*/}.doc ]; then
		echo "<p>"
		sed -n '/\\brief/{s/\\brief //; p}' $RELACSBASE/plugins/$DIR/doc/${DIR##*/}.doc
		echo "</p>"
		echo ""
	    fi
	    if [ -d $RELACSBASE/plugins/$DIR/help ]; then
		echo "    <ul>"
		for PLUGIN in $RELACSBASE/plugins/$DIR/help/*.html; do
 	            PLUGINFILE=${PLUGIN##*/}
		    PLUGINNAME=${PLUGINFILE%%.*}
		    PLUGINNAME=${PLUGINNAME##*-}
                    PLUGINTYPE="$(sed -n -e "/<h2>/{s|<h2>\(.*\) \+\[\(.*\)\]</h2>|\2|; p;}" $PLUGIN )"
		    PLUGINTYPEFILEBASE="$(echo $PLUGINTYPE | tr [:upper:] [:lower:])"
		    IFS=""
		    while read LINE; do
			if [ $(expr match "$LINE" ".*INSERT HERE.*") -gt 0 ]; then
			    sed -e  "1d; \$d; s|<h2>\(.*\) \+\[.*\]</h2>|<h2>\1<span class=\"pluginset\">\&nbsp;\&nbsp;[<a href=\"../${PLUGINTYPEFILEBASE}s.html\">$PLUGINTYPE</a>]\&nbsp;\&nbsp;[<a href=\"index.html\">$DESCR Plugins</a>]</span></h2>|" $PLUGIN
			elif [ $(expr match "$LINE" "PLUGINNAVIGATION.*") -gt 0 ]; then
			    cat navigation.tmp 
			else
			    LINE="${LINE/DATE/$DATE}"
			    echo "${LINE/PLUGINHEADER/$DESCR Plugins: $PLUGINNAME}"
			fi
		    done < $WEBBASE/plugins/plugin.tmpl > $WEBDEST/plugins/${DIR##*/}/$PLUGINFILE
		    IFS="$SAVEIFS"
		    echo "${DIR##*/}/$PLUGINFILE $PLUGINNAME $DESCR" >> ${PLUGINTYPEFILEBASE}plugins.dat
		    echo "      <li><a href=\"$PLUGINFILE\">$PLUGINNAME</a>&nbsp;[<a href=\"../${PLUGINTYPEFILEBASE}s.html\">$PLUGINTYPE</a>]: <span class=\"brief\">$(sed -n '/<h2>/,/<p>/p' $PLUGIN | sed '1d; $d;')</span></li>"
		done
		echo "    </ul>"
	    else
		echo "    <p>Sorry - no plugin descriptions available!</p>"
	    fi
	elif [ $(expr match "$INDEXLINE" "PLUGINNAVIGATION.*") -gt 0 ]; then
	    cat navigation.tmp 
	else
	    INDEXLINE="${INDEXLINE/DATE/$DATE}"
	    echo "${INDEXLINE/PLUGINHEADER/$DESCR Plugins}"
	fi
	IFS=""
    done < $WEBBASE/plugins/plugin.tmpl > $WEBDEST/plugins/${DIR##*/}/index.html
    IFS="$SAVEIFS"
done

# plugin type lists:
for PLUGINTYPE in $PLUGINTYPES; do
    echo "create $PLUGINTYPE plugins index ... "
    IFS=""
    while read INDEXLINE; do
	IFS="$SAVEIFS"
	if [ $(expr match "$INDEXLINE" "PLUGINSETS.*") -gt 0 ]; then
	    echo "    <ul>"
	    while read DIR NAME DESCR; do
		PLUGINSET=""
		for SET in $PLUGINSETS; do
		    PDIR=${SET%%:*}
		    PDESCR=${SET##*:}
		    if test "x$PDESCR" = "x$DESCR"; then
		      PLUGINSET="${PDIR##*/}"
		      break;
		    fi
		done
		echo "      <li><a href=\"${DIR}\">$NAME</a> [<a href=\"$PLUGINSET\">$DESCR</a>]: <span class=\"brief\">$(sed -n '/<h2>.*<span/,/<p>/p' $WEBDEST/plugins/$DIR | sed '1d; $d;')</span></li>"
            done < <(sort -k 2 $(echo $PLUGINTYPE | tr [:upper:] [:lower:])plugins.dat)
	    echo "    </ul>"
	elif [ $(expr match "$INDEXLINE" "PLUGINNAVIGATION.*") -gt 0 ]; then
	    sed 's|../||' navigation.tmp 
	else
	    INDEXLINE="${INDEXLINE/DATE/$DATE}"
	    echo "${INDEXLINE/PLUGINHEADER/$PLUGINTYPE}"
	fi
	IFS=""
    done < $WEBBASE/plugins/plugintype.tmpl > $WEBDEST/plugins/$(echo $PLUGINTYPE | tr [:upper:] [:lower:])s.html
    IFS="$SAVEIFS"
done

#rm -f *plugins.dat
rm navigation.tmp

echo "Ready! You find the relacs website in $WEBDEST"

